name: Build Kernel

on:
  push:
    branches:
      - lineage-21-rel
  pull_request:
    branches:
      - lineage-21-rel


jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/OnionTails/android_kernel_samsung_universal8895
          kernel-branch: lineage-21-rel
          config: .config
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 14
          aosp-clang-version: r518229b
